#line 2 "lexer.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
static yyconst short int yy_acclist[236] =
    {   0,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   62,   60,
       61,   58,   60,   61,   59,   61,   55,   60,   61,   60,
       61,   57,   60,   61,   55,   58,   60,   61,   52,   60,
       61,   55,   60,   61,   51,   52,   60,   61,   60,   61,
       60,   61,   60,   61,   14,   60,   61,   60,   61,   60,
       61,   60,   61,   60,   61,   60,   61,   60,   61,   60,
       61,   60,   61,   56,   60,   61,   61,   58,   61,   55,
       61,   61,   57,   61,   55,   58,   61,   52,   61,   55,
       61,   51,   52,   61,   61,   61,   61,   14,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   56,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   58,   55,   57,   55,   58,   52,
       54,   52,   51,   52,   14,   10,   15,   25,   31,   32,
       33,   28,   29,   30,   53,    3,   52,   12,   10,   11,
       15,    4,    5,   23,   26,   22,   25,   31,   32,   33,
       28,   29,   30,   46,    6,    7,    8,    3,   12,   11,
       34,    4,   13,    5,   23,   26,   22,   35,   46,    6,
        7,    8,    9,   43,   34,   42,   13,   17,   35,   44,
       45,    9,   21,    1,   16,   43,   40,   42,   48,   18,

       17,   24,   44,   45,   49,   50,   21,    2,    1,   16,
       40,   48,   18,   24,   47,   49,   50,    2,   36,   27,
       37,   47,   36,   39,   41,   27,   37,   39,   38,   41,
       38,   20,   20,   19,   19
    } ;

static yyconst short int yy_accept[344] =
    {   0,
        1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       22,   25,   27,   30,   32,   35,   39,   42,   45,   49,
       51,   53,   55,   58,   60,   62,   64,   66,   68,   70,
       72,   74,   77,   78,   80,   82,   83,   85,   88,   90,
       92,   95,   96,   97,   98,  100,  101,  102,  103,  104,
      105,  106,  107,  108,  110,  111,  112,  113,  114,  115,
      116,  117,  118,  119,  120,  121,  122,  123,  124,  125,
      126,  127,  127,  128,  130,  131,  131,  132,  133,  135,
      135,  135,  135,  135,  135,  135,  136,  136,  136,  136,

      136,  136,  136,  137,  137,  137,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  139,  140,  141,  142,  143,  144,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      146,  146,  146,  146,  146,  147,  147,  148,  148,  149,
      149,  149,  149,  150,  151,  151,  152,  152,  152,  152,
      152,  153,  153,  153,  154,  154,  154,  154,  154,  154,
      154,  154,  155,  156,  156,  157,  158,  159,  160,  161,
      162,  163,  164,  164,  164,  164,  164,  165,  165,  165,
      165,  166,  167,  168,  168,  169,  169,  169,  170,  170,

      170,  170,  171,  172,  172,  172,  172,  172,  172,  173,
      173,  174,  175,  175,  175,  175,  175,  175,  175,  176,
      177,  177,  178,  179,  179,  179,  179,  180,  180,  180,
      180,  181,  182,  183,  184,  184,  184,  184,  184,  184,
      185,  186,  186,  186,  186,  186,  187,  187,  188,  188,
      188,  188,  188,  188,  189,  189,  189,  190,  190,  191,
      192,  192,  192,  192,  193,  194,  194,  195,  196,  196,
      197,  197,  197,  198,  199,  200,  200,  200,  200,  201,
      201,  201,  202,  203,  203,  204,  205,  205,  206,  207,
      208,  209,  210,  211,  211,  211,  211,  212,  213,  213,

      213,  213,  214,  214,  215,  215,  216,  217,  218,  219,
      220,  220,  220,  220,  221,  221,  221,  222,  223,  224,
      225,  225,  226,  227,  227,  227,  228,  229,  230,  231,
      231,  231,  232,  232,  232,  233,  233,  234,  234,  234,
      235,  236,  236
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    1,    1,    1,    6,
        6,    9,   10,   11,   10,   12,   13,   14,   15,   16,
       17,   14,   14,   14,   14,   14,   14,   18,    1,    1,
        6,    1,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   20,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   20,
        1,   19,    1,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   20,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   20,    6,    1,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[46] =
    {   0,
        1,    1,    2,    1,    3,    1,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1
    } ;

static yyconst short int yy_base[346] =
    {   0,
        0,    0,   45,    0,   67,    0,   72,   83,   90,   99,
      106,  109,  115,  118,  135,  138,  155,  158,  701,  702,
      118,  702,  101,    0,    0,  194,  187,  147,  194,  116,
      138,  671,  211,  668,  665,  142,  672,  186,  662,  194,
       71,  702,  702,  220,  186,    0,    0,  230,  222,  240,
      236,  151,  661,  665,  253,  662,  667,  659,  135,  661,
       68,  668,  659,  702,  658,  652,  160,  199,  650,  249,
      252,  223,  659,  241,  649,  242,  661,  106,  660,  276,
      238,  673,    0,  280,  278,  669,  702,  283,  290,  644,
      648,  655,  643,  636,  635,  257,  295,  651,  636,  636,

      631,  641,  272,  640,  628,  311,  630,  626,  624,  641,
      628,  632,  622,  625,  293,  315,  628,  635,  631,  235,
      613,  180,  615,  316,  321,  322,  323,  327,  328,  329,
      262,  618,  622,  304,  612,  610,  615,  623,  639,  638,
      606,  610,  609,  616,  334,  619,  329,  617,  336,  616,
      598,  608,  345,  346,  607,  347,  351,  606,  612,  601,
      352,  606,  591,  353,  596,  607,  357,  606,  599,  598,
      585,  358,  359,  593,  363,  364,  365,  369,  370,  371,
      375,  376,  598,  589,  587,  585,  380,  579,  578,  587,
      382,  384,  386,  578,  388,  592,  582,  390,  591,  590,

      571,  392,  394,  396,  588,  398,  569,  582,  402,  569,
      403,  404,  567,  571,  580,  574,  576,  572,  408,  409,
      410,  414,  415,  574,  559,  560,  416,  575,  570,  554,
      420,  421,  422,  427,  572,  561,  566,  559,  556,  431,
      432,  549,  433,  566,  561,  437,  560,  438,  553,  556,
      552,  542,  439,  443,  445,  541,  444,  540,  449,  450,
      551,  540,  538,  451,  455,  550,  457,  462,  551,  466,
      536,  533,  467,  468,  472,  550,  539,  542,  473,  474,
      547,  478,  479,  530,  480,  484,  541,  485,  486,  490,
      492,  496,  497,  540,  535,  526,  498,  502,  523,  536,

      523,  503,  536,  504,  514,  508,  509,  510,  514,  515,
      510,  464,  438,  516,  424,  310,  520,  521,  522,  526,
      276,  527,  528,  261,  263,  532,  533,  534,  538,  255,
      242,  539,  236,  212,  540,  187,  544,  185,  155,  545,
      546,  702,  111,  551,  553
    } ;

static yyconst short int yy_def[346] =
    {   0,
      342,    1,  342,    3,    3,    5,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,  342,  342,
      342,  342,  342,  343,  344,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  343,  344,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  345,  344,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  345,  345,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,

      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,    0,  342,  342,  342
    } ;

static yyconst short int yy_nxt[748] =
    {   0,
       20,   21,   22,   21,   21,   23,   24,   25,   23,   23,
       26,   27,   28,   29,   29,   29,   29,   20,   23,   20,
       30,   20,   31,   32,   33,   20,   34,   20,   35,   20,
       36,   37,   20,   20,   38,   20,   39,   40,   41,   20,
       20,   20,   20,   20,   42,   43,   44,   22,   44,   44,
       45,   46,   47,   45,   45,   48,   49,   50,   51,   51,
       51,   51,   43,   45,   43,   52,   43,   53,   54,   55,
       43,   56,   57,   58,   43,   59,   43,   43,   43,   60,
       43,   43,   61,   62,   43,   43,   63,   43,   43,   64,
       65,  114,   66,   43,   43,   43,  111,   67,   43,   43,

       43,   68,   81,  113,   70,   81,   69,  115,   43,   43,
       43,   43,   71,   43,   82,   70,   43,   43,   43,   80,
       72,   80,   80,   71,   43,   43,   43,   43,   80,   72,
      137,   43,   73,   43,   43,   73,   43,   43,   90,   94,
       43,   43,   43,   43,   43,   43,   43,   43,   81,   74,
       43,   81,   74,   91,   92,   87,   43,   75,   93,   43,
       75,   43,   43,   43,   43,   43,   43,  103,  104,   76,
      102,   94,   76,   90,  103,  104,   77,   78,  340,   77,
       78,   43,   43,   43,   43,   43,   43,   81,   91,   92,
       81,   79,  103,  122,   79,   84,   43,   80,   84,   43,

       85,   85,   85,   85,   80,   88,  154,   89,   89,   89,
       89,   86,   96,  174,  106,   96,  110,  339,   86,  107,
       97,   80,  111,   80,   80,  108,  338,  106,  112,  113,
       80,   84,  123,   80,   84,   85,   85,   85,   85,   81,
       80,   81,   81,   98,   81,  336,   86,   88,   87,   89,
       89,   89,   89,   99,   96,  103,  131,   96,   96,  335,
       86,   96,   97,  125,  126,  127,  128,  129,  130,  106,
      106,  172,  146,  153,  133,  135,  153,   80,  334,   80,
       80,   84,  183,   80,   84,   98,   80,  333,  154,  331,
       80,   85,   85,   85,   85,   99,   85,   85,   85,   85,

      330,   88,   86,   89,   89,   89,   89,   86,  147,  147,
      147,  147,  156,  165,   86,  156,  167,  176,  328,  167,
      176,  166,  177,  178,  179,  177,  178,  179,  180,  181,
      182,  180,  181,  182,  186,  195,  168,  198,  195,  325,
      198,  145,  147,  147,  147,  147,  153,  202,  156,  153,
      202,  156,  204,  209,  212,  204,  209,  212,  167,  219,
      220,  167,  219,  220,  222,  176,  177,  222,  176,  177,
      178,  179,  180,  178,  179,  180,  181,  182,  168,  181,
      182,  227,  205,  231,  227,  232,  231,  233,  232,  195,
      233,  198,  195,  202,  198,  241,  202,  204,  241,  243,

      204,  234,  243,  209,  248,  212,  209,  248,  212,  219,
      220,  255,  219,  220,  255,  222,  257,  227,  222,  257,
      227,  231,  232,  233,  231,  232,  233,  205,  264,  244,
      256,  264,  270,  241,  243,  270,  241,  243,  274,  248,
      280,  274,  248,  280,  282,  257,  255,  282,  257,  255,
      285,  286,  264,  285,  286,  264,  290,  324,  292,  290,
      281,  292,  322,  293,  244,  256,  293,  270,  297,  274,
      270,  297,  274,  298,  302,  280,  298,  302,  280,  282,
      304,  285,  282,  304,  285,  286,  307,  308,  286,  307,
      308,  290,  321,  309,  290,  281,  309,  292,  293,  297,

      292,  293,  297,  298,  302,  304,  298,  302,  304,  318,
      307,  308,  318,  307,  308,  309,  319,  323,  309,  319,
      323,  326,  318,  319,  326,  318,  319,  327,  329,  323,
      327,  329,  323,  326,  327,  332,  326,  327,  332,  329,
      332,  337,  329,  332,  337,  337,  341,  341,  337,  341,
      341,   83,  320,   83,   83,  139,  139,  317,  316,  315,
      314,  313,  312,  311,  310,  306,  305,  303,  301,  300,
      299,  296,  295,  294,  291,  289,  288,  287,  284,  283,
      279,  278,  277,  276,  275,  273,  272,  271,  269,  268,
      267,  266,  265,  263,  262,  261,  260,  259,  258,  254,

      253,  252,  251,  250,  249,  247,  246,  245,  242,  240,
      239,  238,  237,  236,  235,  230,  229,  228,  226,  225,
      224,  223,  221,  218,  217,  216,  215,  214,  213,  211,
      210,  208,  207,  206,  203,  201,  200,  199,  197,  196,
      194,  193,  192,  191,  140,  140,  190,  189,  188,  187,
      185,  184,  175,  173,  171,  170,  169,  164,  163,  162,
      161,  160,  159,  158,  157,  155,  154,  152,  151,  150,
      149,  148,  146,  145,  144,  143,  142,  141,   97,  140,
      138,  136,  134,  132,  124,  121,  120,  119,  114,  106,
      118,  117,  116,   95,   94,  109,  105,  101,  100,   95,

      342,   19,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342
    } ;

static yyconst short int yy_chk[748] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        5,   41,    5,    5,    5,    5,   61,    5,    7,    7,

        7,    5,   23,   61,    7,   23,    5,   41,    5,    8,
        8,    8,    7,    7,  343,    8,    9,    9,    9,   21,
        9,   21,   21,    8,    8,   10,   10,   10,   21,   10,
       78,    9,   11,   11,   11,   12,   12,   12,   30,   78,
       10,   13,   13,   13,   14,   14,   14,   11,   28,   13,
       12,   28,   14,   30,   30,   28,   13,   15,   31,   14,
       16,   15,   15,   15,   16,   16,   16,   59,   59,   15,
       36,   31,   16,   52,   36,   36,   15,   17,  339,   16,
       18,   17,   17,   17,   18,   18,   18,   45,   52,   52,
       45,   17,   67,   67,   18,   26,   17,   26,   26,   18,

       27,   27,   27,   27,   26,   29,  122,   29,   29,   29,
       29,   27,   33,  122,   38,   33,   40,  338,   29,   38,
       33,   44,   40,   44,   44,   38,  336,   68,   40,   40,
       44,   48,   68,   48,   48,   49,   49,   49,   49,   81,
       48,   50,   81,   33,   50,  334,   49,   51,   50,   51,
       51,   51,   51,   33,   55,   72,   72,   55,   96,  333,
       51,   96,   55,   70,   70,   70,   71,   71,   71,   74,
       76,  120,  120,  103,   74,   76,  103,   80,  331,   80,
       80,   84,  131,   84,   84,   55,   80,  330,  131,  325,
       84,   85,   85,   85,   85,   55,   88,   88,   88,   88,

      324,   89,   85,   89,   89,   89,   89,   88,   97,   97,
       97,   97,  106,  115,   89,  106,  116,  124,  321,  116,
      124,  115,  125,  126,  127,  125,  126,  127,  128,  129,
      130,  128,  129,  130,  134,  145,  116,  149,  145,  316,
      149,  134,  147,  147,  147,  147,  153,  154,  156,  153,
      154,  156,  157,  161,  164,  157,  161,  164,  167,  172,
      173,  167,  172,  173,  175,  176,  177,  175,  176,  177,
      178,  179,  180,  178,  179,  180,  181,  182,  167,  181,
      182,  187,  157,  191,  187,  192,  191,  193,  192,  195,
      193,  198,  195,  202,  198,  203,  202,  204,  203,  206,

      204,  193,  206,  209,  211,  212,  209,  211,  212,  219,
      220,  221,  219,  220,  221,  222,  223,  227,  222,  223,
      227,  231,  232,  233,  231,  232,  233,  204,  234,  206,
      221,  234,  240,  241,  243,  240,  241,  243,  246,  248,
      253,  246,  248,  253,  254,  257,  255,  254,  257,  255,
      259,  260,  264,  259,  260,  264,  265,  315,  267,  265,
      253,  267,  313,  268,  243,  255,  268,  270,  273,  274,
      270,  273,  274,  275,  279,  280,  275,  279,  280,  282,
      283,  285,  282,  283,  285,  286,  288,  289,  286,  288,
      289,  290,  312,  291,  290,  280,  291,  292,  293,  297,

      292,  293,  297,  298,  302,  304,  298,  302,  304,  306,
      307,  308,  306,  307,  308,  309,  310,  314,  309,  310,
      314,  317,  318,  319,  317,  318,  319,  320,  322,  323,
      320,  322,  323,  326,  327,  328,  326,  327,  328,  329,
      332,  335,  329,  332,  335,  337,  340,  341,  337,  340,
      341,  344,  311,  344,  344,  345,  345,  305,  303,  301,
      300,  299,  296,  295,  294,  287,  284,  281,  278,  277,
      276,  272,  271,  269,  266,  263,  262,  261,  258,  256,
      252,  251,  250,  249,  247,  245,  244,  242,  239,  238,
      237,  236,  235,  230,  229,  228,  226,  225,  224,  218,

      217,  216,  215,  214,  213,  210,  208,  207,  205,  201,
      200,  199,  197,  196,  194,  190,  189,  188,  186,  185,
      184,  183,  174,  171,  170,  169,  168,  166,  165,  163,
      162,  160,  159,  158,  155,  152,  151,  150,  148,  146,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      133,  132,  123,  121,  119,  118,  117,  114,  113,  112,
      111,  110,  109,  108,  107,  105,  104,  102,  101,  100,
       99,   98,   95,   94,   93,   92,   91,   90,   86,   82,
       79,   77,   75,   73,   69,   66,   65,   63,   62,   60,
       58,   57,   56,   54,   53,   39,   37,   35,   34,   32,

       19,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexer.lex"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#define YY_STACK_USED 1
#line 10 "lexer.lex"
#ifdef WIN32
#pragma warning(disable:4127) // while(1) warning
#pragma warning(disable:4102) // unreferenced label warning
#pragma warning(disable:4505) // unreferenced local function
#pragma warning(disable:4267) // smaller type conversion warnings
#pragma warning(disable:4244) // smaller type conversion warnings
#endif

#include <cstdlib>
#include <stdio.h>
#include <string.h>
#include "parser.yy.h"

int yyline=1;
#define global 1

#define camera 2

#define triangle 3

#define mesh 4

#define instance 5

#define light 6

#define pointlight 7

#define sphere 8

#line 712 "lexer.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 "lexer.lex"


#line 862 "lexer.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 343 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 342 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 49 "lexer.lex"
{ return ENABLE; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "lexer.lex"
{ return DISABLE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "lexer.lex"
{ return MATH_COS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "lexer.lex"
{ return MATH_SIN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "lexer.lex"
{ return MATH_TAN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "lexer.lex"
{ return MATH_ACOS; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "lexer.lex"
{ return MATH_ASIN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "lexer.lex"
{ return MATH_ATAN; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "lexer.lex"
{ return MATH_ATAN2; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "lexer.lex"
{ return MATH_LN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 59 "lexer.lex"
{ return MATH_LOG; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 60 "lexer.lex"
{ return MATH_EXP; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "lexer.lex"
{ return MATH_SQRT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 "lexer.lex"
{ return MATH_E; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 63 "lexer.lex"
{ return MATH_PI; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 65 "lexer.lex"
{ yy_push_state(global); return GLOBAL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 66 "lexer.lex"
{ return WIDTH; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 67 "lexer.lex"
{ return HEIGHT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "lexer.lex"
{ return IMG_BGCOLOR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 69 "lexer.lex"
{ return GL_BGCOLOR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "lexer.lex"
{ yy_push_state(camera); return CAMERA; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "lexer.lex"
{ return POS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "lexer.lex"
{ return DIR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "lexer.lex"
{ return LOOKAT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "lexer.lex"
{ return UP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "lexer.lex"
{ return FOV; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "lexer.lex"
{ yy_push_state(triangle); return TRIANGLE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "lexer.lex"
{ return V1; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "lexer.lex"
{ return V2; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "lexer.lex"
{ return V3; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "lexer.lex"
{ return N1; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "lexer.lex"
{ return N2; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "lexer.lex"
{ return N3; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "lexer.lex"
{ yy_push_state(mesh); return MESH; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "lexer.lex"
{ return LOAD; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "lexer.lex"
{ yy_push_state(instance); return INSTANCE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "lexer.lex"
{ return GEOMETRY; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "lexer.lex"
{ return PUSHMATRIX; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "lexer.lex"
{ return POPMATRIX; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "lexer.lex"
{ return ROTATE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 95 "lexer.lex"
{ return TRANSLATE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 96 "lexer.lex"
{ return SCALE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 98 "lexer.lex"
{ yy_push_state(light); return LIGHT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 99 "lexer.lex"
{ yy_pop_state(); yy_push_state(pointlight); return POINTLIGHT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 100 "lexer.lex"
{ return COLOR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 101 "lexer.lex"
{ return POS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 102 "lexer.lex"
{ return WATTAGE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 104 "lexer.lex"
{ yy_push_state(sphere); return SPHERE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 105 "lexer.lex"
{ return CENTER; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 106 "lexer.lex"
{ return RADIUS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 108 "lexer.lex"
{ yylval.integer = atoi(yytext); return PARSE_INT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 109 "lexer.lex"
{ yylval.real = (float)atof(yytext); return REAL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 "lexer.lex"
{ yylval.str = _strdup(yytext); return STRING; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "lexer.lex"
{ // C style comments
  register int c;
  for ( ; ; ) {
    while ((c = yyinput()) != '*' && c != EOF ) if (c == '\n') yyline++;
    if ( c == '*' ) {
      while ( (c = yyinput()) == '*' ) if (c == '\n') yyline++;
	  if ( c == '/' )
	    break;    /* found the end */
      if ( c == EOF ) {
	    fprintf(stderr, "EOF in comment");
	    printf("Press Enter to continue...");
	  }
	}
  }
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 128 "lexer.lex"
{ return yytext[0]; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 129 "lexer.lex"
{ yy_pop_state(); return yytext[0]; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 130 "lexer.lex"
// eat up comments 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 131 "lexer.lex"
// eat up whitespace
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 132 "lexer.lex"
{ yyline++; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 133 "lexer.lex"
{ printf("\nParse error line %d near: %s\n", yyline, yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "lexer.lex"
ECHO;
	YY_BREAK
#line 1272 "lexer.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(global):
			case YY_STATE_EOF(camera):
			case YY_STATE_EOF(triangle):
			case YY_STATE_EOF(mesh):
			case YY_STATE_EOF(instance):
			case YY_STATE_EOF(light):
			case YY_STATE_EOF(pointlight):
			case YY_STATE_EOF(sphere):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 343 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 343 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 342);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 135 "lexer.lex"

